// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Opplat.Infrastructure.Persistance.Data.Administration;

#nullable disable

namespace Opplat.Infrastructure.Persistance.Migrations.Administration
{
    [DbContext(typeof(AdminTenantCatalogDbContext))]
    [Migration("20260401170858_InitialAdministration")]
    partial class InitialAdministration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.AdminTenantInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DatabaseSchema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AdminTenantInfo");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActorOid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AfterState")
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeState")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("TargetTenantId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TargetTenantIdFk")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TargetUserId")
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2026, 4, 1, 17, 8, 56, 319, DateTimeKind.Utc).AddTicks(3127));

                    b.HasKey("Id");

                    b.HasIndex("ActorOid");

                    b.HasIndex("TargetTenantIdFk");

                    b.HasIndex("TargetUserId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.DatabaseInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConnectionStringReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2026, 4, 1, 17, 8, 56, 467, DateTimeKind.Utc).AddTicks(2676));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("CurrentTenantSchemaCount")
                        .HasColumnType("integer");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("database_instances", (string)null);
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2026, 4, 1, 17, 8, 56, 525, DateTimeKind.Utc).AddTicks(9191));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxActiveUsers")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxApiCallsPerMonth")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxStorageGb")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("PricingMonthly")
                        .HasColumnType("numeric");

                    b.Property<string>("ResourceLimits")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("subscription_plans", (string)null);
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2026, 4, 1, 17, 8, 56, 540, DateTimeKind.Utc).AddTicks(7653));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DatabaseInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DatabaseSchema")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("InactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseInstanceId");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.TenantUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2026, 4, 1, 17, 8, 56, 549, DateTimeKind.Utc).AddTicks(3217));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EntraOid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimaryAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EntraOid")
                        .IsUnique();

                    b.ToTable("tenant_users", (string)null);
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.AuditLog", b =>
                {
                    b.HasOne("Opplat.Domain.Entities.Administration.TenantUser", "Actor")
                        .WithMany("ActorAuditLogs")
                        .HasForeignKey("ActorOid")
                        .HasPrincipalKey("EntraOid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Opplat.Domain.Entities.Administration.Tenant", "TargetTenant")
                        .WithMany("AuditLogs")
                        .HasForeignKey("TargetTenantIdFk")
                        .HasPrincipalKey("Identifier")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Opplat.Domain.Entities.Administration.TenantUser", "TargetUser")
                        .WithMany("TargetUserAuditLogs")
                        .HasForeignKey("TargetUserId")
                        .HasPrincipalKey("EntraOid")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Actor");

                    b.Navigation("TargetTenant");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.Tenant", b =>
                {
                    b.HasOne("Opplat.Domain.Entities.Administration.DatabaseInstance", "DatabaseInstance")
                        .WithMany("Tenants")
                        .HasForeignKey("DatabaseInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Opplat.Domain.Entities.Administration.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Tenants")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatabaseInstance");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.TenantUser", b =>
                {
                    b.HasOne("Opplat.Domain.Entities.Administration.Tenant", "Tenant")
                        .WithMany("TenantUsers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.DatabaseInstance", b =>
                {
                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.SubscriptionPlan", b =>
                {
                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.Tenant", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("TenantUsers");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.TenantUser", b =>
                {
                    b.Navigation("ActorAuditLogs");

                    b.Navigation("TargetUserAuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
