// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Opplat.Infrastructure.Persistance.Data.Administration;

#nullable disable

namespace Opplat.Infrastructure.Persistance.Migrations.Administration
{
    [DbContext(typeof(AdminTenantCatalogDbContext))]
    [Migration("20260826151902_AddSubscriptionBilling")]
    partial class AddSubscriptionBilling
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingInterval")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DatabaseInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("DatabaseSchema")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("InactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("NextBillingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseInstanceId");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.TenantUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EntraOid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimaryAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EntraOid")
                        .IsUnique();

                    b.ToTable("tenant_users", (string)null);
                });

            modelBuilder.Entity("Opplat.Domain.Entities.BaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.AuditLog", b =>
                {
                    b.HasBaseType("Opplat.Domain.Entities.BaseEntity");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActorOid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AfterState")
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeState")
                        .HasColumnType("jsonb");

                    b.Property<string>("TargetTenantId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TargetTenantIdFk")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TargetUserId")
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasIndex("ActorOid");

                    b.HasIndex("TargetTenantIdFk");

                    b.HasIndex("TargetUserId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.DatabaseInstance", b =>
                {
                    b.HasBaseType("Opplat.Domain.Entities.BaseEntity");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentTenantSchemaCount")
                        .HasColumnType("integer");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("database_name");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("database_instances", (string)null);
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.SubscriptionInvoice", b =>
                {
                    b.HasBaseType("Opplat.Domain.Entities.BaseEntity");

                    b.Property<decimal>("AmountDue")
                        .HasColumnType("numeric");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("HostedInvoiceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeInvoiceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasIndex("StripeInvoiceId")
                        .IsUnique();

                    b.HasIndex("TenantId", "PeriodEnd");

                    b.ToTable("subscription_invoices", (string)null);
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.SubscriptionPlan", b =>
                {
                    b.HasBaseType("Opplat.Domain.Entities.BaseEntity");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxActiveUsers")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxApiCallsPerMonth")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxStorageGb")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("PricingAnnual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PricingMonthly")
                        .HasColumnType("numeric");

                    b.Property<string>("ResourceLimits")
                        .HasColumnType("jsonb");

                    b.Property<string>("StripePriceIdAnnual")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StripePriceIdMonthly")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.ToTable("subscription_plans", (string)null);
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.TenantPaymentMethod", b =>
                {
                    b.HasBaseType("Opplat.Domain.Entities.BaseEntity");

                    b.Property<string>("Brand")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long?>("ExpMonth")
                        .HasColumnType("bigint");

                    b.Property<long?>("ExpYear")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Last4")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("StripePaymentMethodId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasIndex("StripePaymentMethodId")
                        .IsUnique();

                    b.HasIndex("TenantId", "IsDefault");

                    b.ToTable("tenant_payment_methods", (string)null);
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.Tenant", b =>
                {
                    b.HasOne("Opplat.Domain.Entities.Administration.DatabaseInstance", "DatabaseInstance")
                        .WithMany("Tenants")
                        .HasForeignKey("DatabaseInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Opplat.Domain.Entities.Administration.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Tenants")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatabaseInstance");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.TenantUser", b =>
                {
                    b.HasOne("Opplat.Domain.Entities.Administration.Tenant", "Tenant")
                        .WithMany("TenantUsers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.AuditLog", b =>
                {
                    b.HasOne("Opplat.Domain.Entities.Administration.TenantUser", "Actor")
                        .WithMany("ActorAuditLogs")
                        .HasForeignKey("ActorOid")
                        .HasPrincipalKey("EntraOid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Opplat.Domain.Entities.Administration.Tenant", "TargetTenant")
                        .WithMany("AuditLogs")
                        .HasForeignKey("TargetTenantIdFk")
                        .HasPrincipalKey("Identifier")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Opplat.Domain.Entities.Administration.TenantUser", "TargetUser")
                        .WithMany("TargetUserAuditLogs")
                        .HasForeignKey("TargetUserId")
                        .HasPrincipalKey("EntraOid")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Actor");

                    b.Navigation("TargetTenant");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.SubscriptionInvoice", b =>
                {
                    b.HasOne("Opplat.Domain.Entities.Administration.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.TenantPaymentMethod", b =>
                {
                    b.HasOne("Opplat.Domain.Entities.Administration.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.Tenant", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("TenantUsers");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.TenantUser", b =>
                {
                    b.Navigation("ActorAuditLogs");

                    b.Navigation("TargetUserAuditLogs");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.DatabaseInstance", b =>
                {
                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Administration.SubscriptionPlan", b =>
                {
                    b.Navigation("Tenants");
                });
#pragma warning restore 612, 618
        }
    }
}
