<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <TrimMode>full</TrimMode>
  </PropertyGroup>

  <ItemGroup>
    <CompileRemove Include="obj\**\*.cs" />
    <CompileRemove Include="bin\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Opplat.Domain\Opplat.Domain.csproj" />
  </ItemGroup>

</Project>
