<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Opplat.Modules.Inventory.Domain.csproj" />
    <ProjectReference Include="..\Infrastructure\Opplat.Modules.Inventory.Infrastructure.csproj" />
  </ItemGroup>
</Project>