<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Finbuckle.MultiTenant.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Opplat.Microservices.Shared\Opplat.Microservices.Shared.csproj" />
    <ProjectReference Include="..\..\..\Opplat.Application\Opplat.Application.csproj" />
    <ProjectReference Include="..\..\..\Modules\Inventory\Domain\Opplat.Modules.Inventory.Domain.csproj" />
  </ItemGroup>

</Project>
