<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Opplat.Application\Opplat.Application.csproj" />
    <ProjectReference Include="..\Opplat.Application.Abstractions\Opplat.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Opplat.Infrastructure\Opplat.Infrastructure.csproj" />
  </ItemGroup>

</Project>
