// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Opplat.Infrastructure.Persistance.Data;

#nullable disable

namespace Opplat.Infrastructure.Persistance.Migrations.Sales
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20260401170948_InitialSales")]
    partial class InitialSales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnnotationOrderDetail", b =>
                {
                    b.Property<Guid>("AnnotationsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderDetailsSaleDetailId")
                        .HasColumnType("uuid");

                    b.HasKey("AnnotationsId", "OrderDetailsSaleDetailId");

                    b.HasIndex("OrderDetailsSaleDetailId");

                    b.ToTable("AnnotationOrderDetail");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Inventory.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ContainerQuantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FixedValue")
                        .HasColumnType("numeric");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<bool>("ItsInventoriable")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ShrinkRatio")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Inventory.ProductClassification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductClassification");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Inventory.ProductGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassificationId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationId");

                    b.ToTable("ProductGroup");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Sales.AddedTopping", b =>
                {
                    b.Property<Guid>("ToppingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SaleDetailId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ToppingId", "SaleDetailId");

                    b.HasIndex("SaleDetailId");

                    b.ToTable("AddedTopping");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Sales.Annotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Annotations");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Sales.CostTab", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ExpectedRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FixedCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PlannedCost")
                        .HasColumnType("numeric");

                    b.Property<string>("Preparation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Presentation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductId");

                    b.ToTable("CostTabs");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Sales.CostTabDetail", b =>
                {
                    b.Property<Guid>("ProductForSaleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CostTabProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("FixedCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("VariableCost")
                        .HasColumnType("numeric");

                    b.HasKey("ProductForSaleId", "ProductId");

                    b.HasIndex("CostTabProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CostTabDetail");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Sales.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsPercent")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.ToTable("Discount");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Sales.OrderDetail", b =>
                {
                    b.Property<Guid>("SaleDetailId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("SaleDetailId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Sales.ProductForSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ProductsForSale");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Sales.ProductTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductTags");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Sales.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Sales.SaleDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quatity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleDetail");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Sales.Topping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Toppings");
                });

            modelBuilder.Entity("ProductForSaleProductTag", b =>
                {
                    b.Property<Guid>("OnProductsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("OnProductsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ProductForSaleProductTag");
                });

            modelBuilder.Entity("ProductForSaleTopping", b =>
                {
                    b.Property<Guid>("AvailableToppingsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OnProductsId")
                        .HasColumnType("uuid");

                    b.HasKey("AvailableToppingsId", "OnProductsId");

                    b.HasIndex("OnProductsId");

                    b.ToTable("ProductForSaleTopping");
                });

            modelBuilder.Entity("AnnotationOrderDetail", b =>
                {
                    b.HasOne("Opplat.Domain.Entities.Sales.Annotation", null)
                        .WithMany()
                        .HasForeignKey("AnnotationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opplat.Domain.Entities.Sales.OrderDetail", null)
                        .WithMany()
                        .HasForeignKey("OrderDetailsSaleDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Inventory.Product", b =>
                {
                    b.HasOne("Opplat.Domain.Entities.Inventory.ProductGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Inventory.ProductGroup", b =>
                {
                    b.HasOne("Opplat.Domain.Entities.Inventory.ProductClassification", "Classification")
                        .WithMany("Groups")
                        .HasForeignKey("ClassificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classification");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Sales.AddedTopping", b =>
                {
                    b.HasOne("Opplat.Domain.Entities.Sales.SaleDetail", "SaleDetail")
                        .WithMany("Toppings")
                        .HasForeignKey("SaleDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opplat.Domain.Entities.Sales.Topping", "Topping")
                        .WithMany()
                        .HasForeignKey("ToppingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaleDetail");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Sales.CostTab", b =>
                {
                    b.HasOne("Opplat.Domain.Entities.Sales.ProductForSale", "Product")
                        .WithOne()
                        .HasForeignKey("Opplat.Domain.Entities.Sales.CostTab", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Sales.CostTabDetail", b =>
                {
                    b.HasOne("Opplat.Domain.Entities.Sales.CostTab", null)
                        .WithMany("Details")
                        .HasForeignKey("CostTabProductId");

                    b.HasOne("Opplat.Domain.Entities.Sales.ProductForSale", "ProductForSale")
                        .WithMany()
                        .HasForeignKey("ProductForSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opplat.Domain.Entities.Inventory.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductForSale");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Sales.Discount", b =>
                {
                    b.HasOne("Opplat.Domain.Entities.Sales.Sale", "Sale")
                        .WithMany("Discounts")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Sales.OrderDetail", b =>
                {
                    b.HasOne("Opplat.Domain.Entities.Sales.SaleDetail", "SaleDetail")
                        .WithOne("OrderDetail")
                        .HasForeignKey("Opplat.Domain.Entities.Sales.OrderDetail", "SaleDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaleDetail");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Sales.SaleDetail", b =>
                {
                    b.HasOne("Opplat.Domain.Entities.Sales.ProductForSale", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opplat.Domain.Entities.Sales.Sale", "Sale")
                        .WithMany("Products")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("ProductForSaleProductTag", b =>
                {
                    b.HasOne("Opplat.Domain.Entities.Sales.ProductForSale", null)
                        .WithMany()
                        .HasForeignKey("OnProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opplat.Domain.Entities.Sales.ProductTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductForSaleTopping", b =>
                {
                    b.HasOne("Opplat.Domain.Entities.Sales.Topping", null)
                        .WithMany()
                        .HasForeignKey("AvailableToppingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opplat.Domain.Entities.Sales.ProductForSale", null)
                        .WithMany()
                        .HasForeignKey("OnProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Inventory.ProductClassification", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Sales.CostTab", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Sales.Sale", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Opplat.Domain.Entities.Sales.SaleDetail", b =>
                {
                    b.Navigation("OrderDetail");

                    b.Navigation("Toppings");
                });
#pragma warning restore 612, 618
        }
    }
}
