// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using notificationsWebApi.Data;

namespace notificationsWebApi.Migrations
{
    [DbContext(typeof(notificationsDbContext))]
    [Migration("20190925223558_Primera")]
    partial class Primera
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("notificationsWebApi.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Link");

                    b.Property<string>("Modulo");

                    b.Property<string>("Texto");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("notificationsWebApi.Models.UserNotification", b =>
                {
                    b.Property<int>("NotificationId");

                    b.Property<string>("UsuarioId");

                    b.Property<bool>("IsRead");

                    b.HasKey("NotificationId", "UsuarioId");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("notificationsWebApi.Models.UserNotification", b =>
                {
                    b.HasOne("notificationsWebApi.Models.Notification", "Notification")
                        .WithMany("UserNotification")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
