<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Opplat.Application.Abstractions\Opplat.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Opplat.Domain\Opplat.Domain.csproj" />
    <ProjectReference Include="..\Opplat.Infrastructure\Opplat.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="mailkit" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
  </ItemGroup>

</Project>
