// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using opplatApplication.Data;

namespace opplatApplication.Migrations
{
    [DbContext(typeof(OpplatAppDbContext))]
    partial class OpplatAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("opplatApplication.Models.Licencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Aplicacion");

                    b.Property<byte[]>("Hash");

                    b.Property<string>("Subscriptor");

                    b.Property<DateTime>("Vencimiento");

                    b.HasKey("Id");

                    b.ToTable("Licencias");
                });
#pragma warning restore 612, 618
        }
    }
}
