// <auto-generated />
using InventarioWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace InventarioWebApi.Migrations
{
    [DbContext(typeof(InventarioDbContext))]
    [Migration("20191008205401_primera")]
    partial class primera
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("InventarioWebApi.Models.Almacen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Codigo")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Almacenes");
                });

            modelBuilder.Entity("InventarioWebApi.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("InventarioWebApi.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoriaId");

                    b.Property<string>("Codigo")
                        .IsRequired();

                    b.Property<string>("Descripcion");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<decimal>("PrecioCompraMlc")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecioCompraMn")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecioVentaMlc")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecioVentaMn")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TipoId");

                    b.Property<int>("UnidadId");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("TipoId");

                    b.HasIndex("UnidadId");

                    b.ToTable("Productos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Producto");
                });

            modelBuilder.Entity("InventarioWebApi.Models.Submayor", b =>
                {
                    b.Property<int>("AlmacenId");

                    b.Property<int>("ProductoId");

                    b.Property<decimal>("Cantidad");

                    b.Property<int>("UnidadId");

                    b.HasKey("AlmacenId", "ProductoId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UnidadId");

                    b.ToTable("Submayores");
                });

            modelBuilder.Entity("InventarioWebApi.Models.TipoDeProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("TipoDeProducto");
                });

            modelBuilder.Entity("InventarioWebApi.Models.UnidadDeMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<string>("Unidad")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("UnidadDeMedida");
                });

            modelBuilder.Entity("InventarioWebApi.Models.Derivado", b =>
                {
                    b.HasBaseType("InventarioWebApi.Models.Producto");

                    b.Property<int>("ProductoOrigenId");

                    b.HasIndex("ProductoOrigenId");

                    b.HasDiscriminator().HasValue("Derivado");
                });

            modelBuilder.Entity("InventarioWebApi.Models.Producto", b =>
                {
                    b.HasOne("InventarioWebApi.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InventarioWebApi.Models.TipoDeProducto", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InventarioWebApi.Models.UnidadDeMedida", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InventarioWebApi.Models.Submayor", b =>
                {
                    b.HasOne("InventarioWebApi.Models.Almacen", "Almacen")
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InventarioWebApi.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InventarioWebApi.Models.UnidadDeMedida", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InventarioWebApi.Models.Derivado", b =>
                {
                    b.HasOne("InventarioWebApi.Models.Producto", "ProductoOrigen")
                        .WithMany("Derivados")
                        .HasForeignKey("ProductoOrigenId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
